# ./docker-compose.yml

version: '3'

services:
  mysql:
    image: mysql:8
    ports:
      - '3307:3306'
    volumes:
      - ./local-data/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    depends_on:
      - mysql
  web:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/html/
    ports:
      - '8100:80'
    stdin_open: true
    tty: true
